Resolve breaking issues from upgrade + Added chart features
okendo/okendo-ngx-charts pull request #2
Opened 2021-12-13 05:05 UTC by chenglouokendo

This PR addresses several issues encountered during ngx-charts update process and also adds various features and options to better customise the charts.

2021-12-13 22:31 UTC, rachaelfulcher approved these changes

2021-12-14 07:10 UTC, mattgarven requested changes
Some minor whitespace fixes and general comments / questions

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/bar-chart/series-vertical.component.ts
> +          topNameOfGroup = this.series[i].name;
```suggestion
        topNameOfGroup = this.series[i].name;
```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/common/area.component.ts
> +
```suggestion

```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/common/svg-linear-gradient.component.ts
> +
```suggestion

```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/line-chart/line-chart.component.ts
> +
```suggestion

```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/line-chart/line-series.component.ts
> +      const values = this.data.series.map(d => d.value);
```suggestion
      const values = this.data.series.map(d => d.value);
```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/line-chart/line-series.component.ts
> +
```suggestion

```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/line-chart/line-series.component.ts
> +
```suggestion

```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/line-chart/line-series.component.ts
> +
```suggestion

```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/line-chart/line-series.component.ts
> +
```suggestion

```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/utils/visibility-observer.ts
> +  runCheck(): void {
```suggestion
  runCheck(): void {
```

2021-12-14 07:10 UTC, mattgarven commented on src/app/app.component.ts
> +    if (this.chart.inputFormat === 'calendarData') this.calendarData = this.getCalendarData();
```suggestion
    if (this.chart.inputFormat === 'calendarData') this.calendarData = this.getCalendarData();
```

2021-12-14 07:10 UTC, mattgarven commented on src/app/app.component.ts
> +
```suggestion

```

2021-12-14 07:10 UTC, mattgarven commented on src/app/custom-charts/sparkline/sparkline.component.ts
> +
```suggestion

```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/models/chart-data.model.ts
> +  extra?: any;
is `extra` used elsewhere or just for the `gradientDirection` property?

consider something like:
```suggestion
  extra?: {
    gradientDirection?: string;
  };
```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/line-chart/line-series.component.ts
> +    }
```suggestion
    }
```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/line-chart/line-series.component.ts
> +      this.areaGradientStops = this.colors.getLinearGradientStops(max);
```suggestion
      this.areaGradientStops = this.colors.getLinearGradientStops(max);
```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/line-chart/line-series.component.ts
> +      const values = this.data.series.map(d => d.value);
```suggestion
      const values = this.data.series.map(d => d.value);
```

2021-12-14 07:10 UTC, mattgarven commented on projects/swimlane/ngx-charts/src/lib/common/base-chart.component.ts
> +    if (hostElem && hostElem.parentNode !== null) {
what did the `isPlatformBrowser` check do and is it safe to remove?

2021-12-17 04:12 UTC, closed without merging